### ISSUE TITLE
Calendar Datepicker muncul dibalik elemen lain

### ISSUE THREAD

**Issue by silotester** [yacanet/silo#8]
Saat diklik icon calender pada datepicker, pickernya muncul dibalik elemen html lain.

**Comment by mrizkir** [comment]
Fixed. Tambahkan di file silo.css :

.TDatePicker_default
{  
    z-index:2;
}

**Comment by mrizkir** [comment]
Fixed. Tambahkan di file silo.css :

.TDatePicker_default
{  
    z-index:2;
}
